version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

brews:
  - name: cast
    repository:
      owner: neosapience
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/neosapience/cast
    description: Typecast Text-to-Speech CLI
    license: MIT
    install: |
      bin.install "cast"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
